const List<String> icons = [
  // 😊 Yüzler ve Duygular (Smileys & Emotion)
  '😀',
  '😁',
  '😂',
  '🤣',
  '😃',
  '😄',
  '😅',
  '😆',
  '😉',
  '😊',
  '😋',
  '😎',
  '😍',
  '😘',
  '🥰',
  '😗',
  '😙',
  '😚',
  '🙂',
  '🤗',
  '🤔',
  '😐',
  '😑',
  '😶',
  '🙄',
  '😏',
  '😣',
  '😥',
  '😮',
  '🤐',
  '😯',
  '😪',
  '😫',
  '🥱',
  '😴',
  '😌',
  '😛',
  '😜',
  '🤤',
  '😝',
  '🤪',
  '🤓',
  '🧐',
  '😒',
  '😞',
  '😔',
  '😟',
  '😕',
  '🙃',
  '☹️',
  '😣',
  '😖',
  '😫',
  '😩',
  '🥺',
  '😢',
  '😭',
  '😤',
  '😠',
  '😡',
  '🤬',
  '🤯',
  '😳',
  '🥵',
  '🥶',
  '😱',
  '😨',
  '😰',
  '😥',
  '😓',
  '🤗',
  '🤭',
  '🤫',
  '🤥',
  '😶‍🌫️',
  '😐‍',
  '😬',
  '🙄',
  '😯',
  '😦',
  '😧',
  '😮',
  '😲',
  '🥱',
  '😴',
  '🤤',
  '😪',
  '😵',
  '🤐',
  '🥴',
  '🤢',
  '🤮',
  '🤧',
  '😷',
  '🤒',
  '🤕',
  '🤑',
  '🤠',
  '😈',
  '👿',

  // 👋 İnsanlar & Vücut (People & Body)
  '👋',
  '🤚',
  '🖐️',
  '✋',
  '🖖',
  '👌',
  '🤌',
  '🤏',
  '✌️',
  '🤞',
  '🤟',
  '🤘',
  '🤙',
  '👈',
  '👉',
  '👆',
  '🖕',
  '👇',
  '☝️',
  '👍',
  '👎',
  '✊',
  '👊',
  '🤛',
  '🤜',
  '👏',
  '🙌',
  '🫶',
  '👐',
  '🤲',
  '🤝',
  '🙏',
  '💅',
  '🤳',
  '💪',
  '🦾',
  '🦵',
  '🦶',
  '👂',
  '🦻',
  '👃',
  '👀',
  '👁️',
  '🧠',
  '🫀',
  '🫁',
  '🦷',
  '🦴',
  '👅',
  '👄',
  '🫦',
  '👶',
  '👧',
  '🧒',
  '👦',
  '👩',
  '🧑',
  '👨',
  '👩‍🦱',
  '👨‍🦱',
  '🧔',
  '🧓',
  '👵',
  '👴',
  '👮',
  '👷',
  '💂',
  '🕵️',
  '👩‍⚕️',
  '👨‍⚕️',
  '👩‍🏫',
  '👨‍🏫',
  '👩‍💻',
  '👨‍💻',
  '👩‍🍳',
  '👨‍🍳',
  '👩‍🎤',
  '👨‍🎤',
  '👩‍✈️',
  '👨‍✈️',
  '👩‍🚀',
  '👨‍🚀',
  '👩‍🚒',
  '👨‍🚒',
  '🧑‍🎓',
  '👰',
  '🤵',
  '👸',
  '🤴',
  '🥷',
  '🧙',
  '🧚',
  '🧛',
  '🧜',
  '🧝',
  '🧞',
  '🧟',

  // 🐶 Hayvanlar & Doğa (Animals & Nature)
  '🐶',
  '🐱',
  '🐭',
  '🐹',
  '🐰',
  '🦊',
  '🐻',
  '🐼',
  '🐨',
  '🐯',
  '🦁',
  '🐮',
  '🐷',
  '🐸',
  '🐵',
  '🙈',
  '🙉',
  '🙊',
  '🐔',
  '🐧',
  '🐦',
  '🐤',
  '🐣',
  '🐥',
  '🦆',
  '🦅',
  '🦉',
  '🦇',
  '🐺',
  '🐗',
  '🐴',
  '🦄',
  '🐝',
  '🐛',
  '🦋',
  '🐌',
  '🐞',
  '🐜',
  '🦟',
  '🪲',
  '🕷️',
  '🕸️',
  '🦂',
  '🐢',
  '🐍',
  '🦎',
  '🐙',
  '🦑',
  '🦐',
  '🦞',
  '🦀',
  '🐡',
  '🐠',
  '🐟',
  '🐬',
  '🐳',
  '🐋',
  '🦈',
  '🐊',
  '🐅',
  '🐆',
  '🦓',
  '🦍',
  '🦧',
  '🐘',
  '🦣',
  '🦒',
  '🦘',
  '🦬',
  '🐂',
  '🐃',
  '🐄',
  '🐎',
  '🐖',
  '🐏',
  '🐑',
  '🦙',
  '🐐',
  '🦌',
  '🐕',
  '🐩',
  '🐈',
  '🐓',
  '🦃',
  '🕊️',
  '🐇',
  '🐁',
  '🐀',
  '🐿️',
  '🦔',

  // 🍎 Yiyecek & İçecek (Food & Drink)
  '🍏',
  '🍎',
  '🍐',
  '🍊',
  '🍋',
  '🍌',
  '🍉',
  '🍇',
  '🍓',
  '🫐',
  '🍈',
  '🍒',
  '🍑',
  '🥭',
  '🍍',
  '🥥',
  '🥝',
  '🍅',
  '🍆',
  '🥑',
  '🥦',
  '🥬',
  '🥒',
  '🌶️',
  '🌽',
  '🥕',
  '🧄',
  '🧅',
  '🥔',
  '🍠',
  '🥐',
  '🍞',
  '🥖',
  '🥨',
  '🧀',
  '🥚',
  '🍳',
  '🥞',
  '🧇',
  '🥓',
  '🥩',
  '🍗',
  '🍖',
  '🌭',
  '🍔',
  '🍟',
  '🍕',
  '🥪',
  '🥙',
  '🌮',
  '🌯',
  '🥗',
  '🥘',
  '🥫',
  '🍝',
  '🍜',
  '🍲',
  '🍛',
  '🍣',
  '🍱',
  '🥟',
  '🍤',
  '🍙',
  '🍚',
  '🍘',
  '🍢',
  '🍡',
  '🍧',
  '🍨',
  '🍦',
  '🥧',
  '🍰',
  '🎂',
  '🧁',
  '🍮',
  '🍭',
  '🍬',
  '🍫',
  '🍿',
  '🍩',
  '🍪',
  '☕️',
  '🍵',
  '🥤',
  '🧃',
  '🍷',
  '🍸',
  '🍹',
  '🍺',
  '🍻',
  '🥂',
  '🥃',
  '🧉',
  '🧊',

  // 🧳 Seyahat & Yerler (Travel & Places)
  '🌍',
  '🌎',
  '🌏',
  '🗺️',
  '🗾',
  '🏔️',
  '⛰️',
  '🌋',
  '🗻',
  '🏕️',
  '🏖️',
  '🏜️',
  '🏝️',
  '🏞️',
  '🏟️',
  '🏛️',
  '🏗️',
  '🧱',
  '🏠',
  '🏡',
  '🏢',
  '🏣',
  '🏤',
  '🏥',
  '🏦',
  '🏨',
  '🏩',
  '🏪',
  '🏫',
  '🏬',
  '🏭',
  '🏯',
  '🏰',
  '💒',
  '🗼',
  '🗽',
  '⛪️',
  '🕌',
  '🕍',
  '⛩️',
  '🕋',
  '⛲️',
  '⛺️',
  '🌁',
  '🌃',
  '🏙️',
  '🌄',
  '🌅',
  '🌆',
  '🌇',
  '🌉',
  '🌌',
  '🎠',
  '🎡',
  '🎢',
  '🚂',
  '🚃',
  '🚄',
  '🚅',
  '🚆',
  '🚇',
  '🚈',
  '🚉',
  '🚊',
  '🚝',
  '🚞',
  '🚋',
  '🚌',
  '🚍',
  '🚎',
  '🚐',
  '🚑',
  '🚒',
  '🚓',
  '🚔',
  '🚕',
  '🚖',
  '🚗',
  '🚘',
  '🚙',
  '🏎️',
  '🚚',
  '🚛',
  '🚜',
  '🛻',
  '🚲',
  '🛴',
  '🛹',
  '🛼',
  '🛵',
  '🏍️',
  '🛺',
  '✈️',
  '🛫',
  '🛬',
  '🪂',
  '💺',
  '🚁',
  '🛰️',
  '🚀',
  '🛸',
  '🚢',
  '⚓️',
  '🪝',

  // 💡 Objeler (Objects)
  '⌚️',
  '📱',
  '💻',
  '⌨️',
  '🖥️',
  '🖨️',
  '🖱️',
  '💾',
  '💿',
  '📀',
  '🎥',
  '🎞️',
  '📷',
  '📸',
  '📹',
  '📺',
  '📻',
  '🎙️',
  '🎚️',
  '🎛️',
  '☎️',
  '📞',
  '📟',
  '📠',
  '🔋',
  '🔌',
  '💡',
  '🔦',
  '🕯️',
  '🧯',
  '🪔',
  '🧲',
  '🧪',
  '🧫',
  '🧬',
  '🩸',
  '💊',
  '💉',
  '🩹',
  '🩼',
  '🩺',
  '🧷',
  '🧹',
  '🧺',
  '🪣',
  '🧻',
  '🪟',
  '🪞',
  '🚪',
  '🛏️',
  '🪑',
  '🚽',
  '🚿',
  '🛁',
  '🪠',
  '🧴',
  '🪥',
  '🪒',
  '🧼',
  '🪮',
  '🪶',
  '🧽',
  '🧹',
  '🧺',
  '🧯',
  '🪣',
  '🧸',
  '🎁',
  '🎈',
  '🎉',
  '🎊',
  '🎀',
  '🎗️',
  '🏆',
  '🥇',
  '🥈',
  '🥉',
  '🏅',
  '🎖️',
  '🧿',
  '📿',
  '💎',

  // ❤️ Semboller (Symbols)
  '❤️',
  '🧡',
  '💛',
  '💚',
  '💙',
  '💜',
  '🤍',
  '🤎',
  '🖤',
  '💔',
  '❣️',
  '💕',
  '💞',
  '💓',
  '💗',
  '💖',
  '💘',
  '💝',
  '💟',
  '☮️',
  '✝️',
  '☪️',
  '🕉️',
  '☸️',
  '🪯',
  '✡️',
  '🔯',
  '🕎',
  '☯️',
  '☦️',
  '🛐',
  '⛎',
  '♈️',
  '♉️',
  '♊️',
  '♋️',
  '♌️',
  '♍️',
  '♎️',
  '♏️',
  '♐️',
  '♑️',
  '♒️',
  '♓️',
  '🆔',
  '⚛️',
  '🉑',
  '☢️',
  '☣️',
  '📴',
  '📳',
  '🈶',
  '🈚️',
  '🈸',
  '🈺',
  '🈷️',
  '✴️',
  '🆚',
  '💯',
  '🈴',
  '🈵',
  '🈹',
  '🈲',
  '🅰️',
  '🅱️',
  '🆎',
  '🆑',
  '🅾️',
  '🆘',
  '❌',
  '⭕️',
  '🛑',
  '⛔️',
  '📛',
  '🚫',
  '💢',
  '♨️',
  '🚷',
  '🚯',
  '🚳',
  '🚱',
  '🔞',
  '📵',
  '🚭',
  '❗️',
  '❕',
  '❓',
  '❔',
  '‼️',
  '⁉️',
  '🔅',
  '🔆',
  '〽️',
  '⚠️',
  '🚸',
  '🔱',
  '⚜️',
  '🔰',
  '♻️',
  '✅',
  '🈯️',
  '💹',
  '❇️',
  '✳️',
  '❎',
  '🌐',
  '💠',
  'Ⓜ️',
  '🌀',
  '🅾️',
  '🅿️',
  '🛐',
  '🔺',
  '🔻',
  '💤',
  '🏧',
  '🚾',
  '♿️',
  '🅿️',
  '🅱️',
  '🚹',
  '🚺',
  '🚼',
  '🚻',
  '🚮',
  '🎦',
  '📶',
  '🈁',
  '🔣',
  'ℹ️',
  '🔤',
  '🔡',
  '🔠',
  '🆖',
  '🆗',
  '🆙',
  '🆒',
  '🆕',
  '🆓',
  '0️⃣',
  '1️⃣',
  '2️⃣',
  '3️⃣',
  '4️⃣',
  '5️⃣',
  '6️⃣',
  '7️⃣',
  '8️⃣',
  '9️⃣',
  '🔟',
];

final Map<String, String> iconNames = {
  // 😊 Yüzler ve Duygular (Smileys & Emotion)
  '😀': 'Grinning Face',
  '😁': 'Beaming Face with Smiling Eyes',
  '😂': 'Face with Tears of Joy',
  '🤣': 'Rolling on the Floor Laughing',
  '😃': 'Grinning Face with Big Eyes',
  '😄': 'Grinning Face with Smiling Eyes',
  '😅': 'Grinning Face with Sweat',
  '😆': 'Grinning Squinting Face',
  '😉': 'Winking Face',
  '😊': 'Smiling Face with Smiling Eyes',
  '😋': 'Face Savoring Food',
  '😎': 'Smiling Face with Sunglasses',
  '😍': 'Smiling Face with Heart-Eyes',
  '😘': 'Face Blowing a Kiss',
  '🥰': 'Smiling Face with Hearts',
  '😗': 'Kissing Face',
  '😙': 'Kissing Face with Smiling Eyes',
  '😚': 'Kissing Face with Closed Eyes',
  '🙂': 'Slightly Smiling Face',
  '🤗': 'Hugging Face',
  '🤔': 'Thinking Face',
  '😐': 'Neutral Face',
  '😑': 'Expressionless Face',
  '😶': 'Face Without Mouth',
  '🙄': 'Face with Rolling Eyes',
  '😏': 'Smirking Face',
  '😣': 'Persevering Face',
  '😥': 'Sad but Relieved Face',
  '😮': 'Face with Open Mouth',
  '🤐': 'Zipper-Mouth Face',
  '😯': 'Hushed Face',
  '😪': 'Sleepy Face',
  '😫': 'Tired Face',
  '🥱': 'Yawning Face',
  '😴': 'Sleeping Face',
  '😌': 'Relieved Face',
  '😛': 'Face with Tongue',
  '😜': 'Winking Face with Tongue',
  '🤤': 'Drooling Face',
  '😝': 'Squinting Face with Tongue',
  '🤪': 'Zany Face',
  '🤓': 'Nerd Face',
  '🧐': 'Face with Monocle',
  '😒': 'Unamused Face',
  '😞': 'Disappointed Face',
  '😔': 'Pensive Face',
  '😟': 'Worried Face',
  '😕': 'Confused Face',
  '🙃': 'Upside-Down Face',
  '☹️': 'Frowning Face',
  '😖': 'Confounded Face',
  '😩': 'Weary Face',
  '🥺': 'Pleading Face',
  '😢': 'Crying Face',
  '😭': 'Loudly Crying Face',
  '😤': 'Face with Steam From Nose',
  '😠': 'Angry Face',
  '😡': 'Pouting Face',
  '🤬': 'Face with Symbols on Mouth',
  '🤯': 'Exploding Head',
  '😳': 'Flushed Face',
  '🥵': 'Hot Face',
  '🥶': 'Cold Face',
  '😱': 'Face Screaming in Fear',
  '😨': 'Fearful Face',
  '😰': 'Anxious Face with Sweat',
  '😓': 'Downcast Face with Sweat',
  '🤭': 'Face with Hand Over Mouth',
  '🤫': 'Shushing Face',
  '🤥': 'Lying Face',
  '😶‍🌫️': 'Face in Clouds',
  '😐‍': 'Neutral Face with Dotted Line',
  '😬': 'Grimacing Face',
  '😦': 'Frowning Face with Open Mouth',
  '😧': 'Anguished Face',
  '😲': 'Astonished Face',
  '😵': 'Dizzy Face',
  '🥴': 'Woozy Face',
  '🤢': 'Nauseated Face',
  '🤮': 'Face Vomiting',
  '🤧': 'Sneezing Face',
  '😷': 'Face with Medical Mask',
  '🤒': 'Face with Thermometer',
  '🤕': 'Face with Head-Bandage',
  '🤑': 'Money-Mouth Face',
  '🤠': 'Cowboy Hat Face',
  '😈': 'Smiling Face with Horns',
  '👿': 'Angry Face with Horns',

  // 👋 İnsanlar & Vücut (People & Body)
  '👋': 'Waving Hand',
  '🤚': 'Raised Back of Hand',
  '🖐️': 'Hand with Fingers Splayed',
  '✋': 'Raised Hand',
  '🖖': 'Vulcan Salute',
  '👌': 'OK Hand',
  '🤌': 'Pinched Fingers',
  '🤏': 'Pinching Hand',
  '✌️': 'Victory Hand',
  '🤞': 'Crossed Fingers',
  '🤟': 'Love-You Gesture',
  '🤘': 'Sign of the Horns',
  '🤙': 'Call Me Hand',
  '👈': 'Backhand Index Pointing Left',
  '👉': 'Backhand Index Pointing Right',
  '👆': 'Backhand Index Pointing Up',
  '🖕': 'Middle Finger',
  '👇': 'Backhand Index Pointing Down',
  '☝️': 'Index Pointing Up',
  '👍': 'Thumbs Up',
  '👎': 'Thumbs Down',
  '✊': 'Raised Fist',
  '👊': 'Oncoming Fist',
  '🤛': 'Left-Facing Fist',
  '🤜': 'Right-Facing Fist',
  '👏': 'Clapping Hands',
  '🙌': 'Raising Hands',
  '🫶': 'Heart Hands',
  '👐': 'Open Hands',
  '🤲': 'Palms Up Together',
  '🤝': 'Handshake',
  '🙏': 'Folded Hands',
  '💅': 'Nail Polish',
  '🤳': 'Selfie',
  '💪': 'Flexed Biceps',
  '🦾': 'Mechanical Arm',
  '🦵': 'Leg',
  '🦶': 'Foot',
  '👂': 'Ear',
  '🦻': 'Ear with Hearing Aid',
  '👃': 'Nose',
  '👀': 'Eyes',
  '👁️': 'Eye',
  '🧠': 'Brain',
  '🫀': 'Anatomical Heart',
  '🫁': 'Lungs',
  '🦷': 'Tooth',
  '🦴': 'Bone',
  '👅': 'Tongue',
  '👄': 'Mouth',
  '🫦': 'Biting Lip',
  '👶': 'Baby',
  '👧': 'Girl',
  '🧒': 'Child',
  '👦': 'Boy',
  '👩': 'Woman',
  '🧑': 'Person',
  '👨': 'Man',
  '👩‍🦱': 'Woman: Curly Hair',
  '👨‍🦱': 'Man: Curly Hair',
  '🧔': 'Person with Beard',
  '🧓': 'Older Person',
  '👵': 'Older Woman',
  '👴': 'Older Man',
  '👮': 'Police Officer',
  '👷': 'Construction Worker',
  '💂': 'Guard',
  '🕵️': 'Detective',
  '👩‍⚕️': 'Woman Health Worker',
  '👨‍⚕️': 'Man Health Worker',
  '👩‍🏫': 'Woman Teacher',
  '👨‍🏫': 'Man Teacher',
  '👩‍💻': 'Woman Technologist',
  '👨‍💻': 'Man Technologist',
  '👩‍🍳': 'Woman Cook',
  '👨‍🍳': 'Man Cook',
  '👩‍🎤': 'Woman Singer',
  '👨‍🎤': 'Man Singer',
  '👩‍✈️': 'Woman Pilot',
  '👨‍✈️': 'Man Pilot',
  '👩‍🚀': 'Woman Astronaut',
  '👨‍🚀': 'Man Astronaut',
  '👩‍🚒': 'Woman Firefighter',
  '👨‍🚒': 'Man Firefighter',
  '🧑‍🎓': 'Student',
  '👰': 'Bride with Veil',
  '🤵': 'Person in Tuxedo',
  '👸': 'Princess',
  '🤴': 'Prince',
  '🥷': 'Ninja',
  '🧙': 'Mage',
  '🧚': 'Fairy',
  '🧛': 'Vampire',
  '🧜': 'Merperson',
  '🧝': 'Elf',
  '🧞': 'Genie',
  '🧟': 'Zombie',

  // 🐶 Hayvanlar & Doğa (Animals & Nature)
  '🐶': 'Dog Face',
  '🐱': 'Cat Face',
  '🐭': 'Mouse Face',
  '🐹': 'Hamster',
  '🐰': 'Rabbit Face',
  '🦊': 'Fox',
  '🐻': 'Bear',
  '🐼': 'Panda',
  '🐨': 'Koala',
  '🐯': 'Tiger Face',
  '🦁': 'Lion',
  '🐮': 'Cow Face',
  '🐷': 'Pig Face',
  '🐸': 'Frog',
  '🐵': 'Monkey Face',
  '🙈': 'See-No-Evil Monkey',
  '🙉': 'Hear-No-Evil Monkey',
  '🙊': 'Speak-No-Evil Monkey',
  '🐔': 'Chicken',
  '🐧': 'Penguin',
  '🐦': 'Bird',
  '🐤': 'Baby Chick',
  '🐣': 'Hatching Chick',
  '🐥': 'Front-Facing Baby Chick',
  '🦆': 'Duck',
  '🦅': 'Eagle',
  '🦉': 'Owl',
  '🦇': 'Bat',
  '🐺': 'Wolf',
  '🐗': 'Boar',
  '🐴': 'Horse Face',
  '🦄': 'Unicorn',
  '🐝': 'Honeybee',
  '🐛': 'Bug',
  '🦋': 'Butterfly',
  '🐌': 'Snail',
  '🐞': 'Lady Beetle',
  '🐜': 'Ant',
  '🦟': 'Mosquito',
  '🪲': 'Beetle',
  '🕷️': 'Spider',
  '🕸️': 'Spider Web',
  '🦂': 'Scorpion',
  '🐢': 'Turtle',
  '🐍': 'Snake',
  '🦎': 'Lizard',
  '🐙': 'Octopus',
  '🦑': 'Squid',
  '🦐': 'Shrimp',
  '🦞': 'Lobster',
  '🦀': 'Crab',
  '🐡': 'Blowfish',
  '🐠': 'Tropical Fish',
  '🐟': 'Fish',
  '🐬': 'Dolphin',
  '🐳': 'Spouting Whale',
  '🐋': 'Whale',
  '🦈': 'Shark',
  '🐊': 'Crocodile',
  '🐅': 'Tiger',
  '🐆': 'Leopard',
  '🦓': 'Zebra',
  '🦍': 'Gorilla',
  '🦧': 'Orangutan',
  '🐘': 'Elephant',
  '🦣': 'Mammoth',
  '🦒': 'Giraffe',
  '🦘': 'Kangaroo',
  '🦬': 'Bison',
  '🐂': 'Ox',
  '🐃': 'Water Buffalo',
  '🐄': 'Cow',
  '🐎': 'Horse',
  '🐖': 'Pig',
  '🐏': 'Ram',
  '🐑': 'Ewe',
  '🦙': 'Llama',
  '🐐': 'Goat',
  '🦌': 'Deer',
  '🐕': 'Dog',
  '🐩': 'Poodle',
  '🐈': 'Cat',
  '🐓': 'Rooster',
  '🦃': 'Turkey',
  '🕊️': 'Dove',
  '🐇': 'Rabbit',
  '🐁': 'Mouse',
  '🐀': 'Rat',
  '🐿️': 'Chipmunk',
  '🦔': 'Hedgehog',

  // 🍎 Yiyecek & İçecek (Food & Drink)
  '🍏': 'Green Apple',
  '🍎': 'Red Apple',
  '🍐': 'Pear',
  '🍊': 'Tangerine',
  '🍋': 'Lemon',
  '🍌': 'Banana',
  '🍉': 'Watermelon',
  '🍇': 'Grapes',
  '🍓': 'Strawberry',
  '🫐': 'Blueberries',
  '🍈': 'Melon',
  '🍒': 'Cherries',
  '🍑': 'Peach',
  '🥭': 'Mango',
  '🍍': 'Pineapple',
  '🥥': 'Coconut',
  '🥝': 'Kiwifruit',
  '🍅': 'Tomato',
  '🍆': 'Eggplant',
  '🥑': 'Avocado',
  '🥦': 'Broccoli',
  '🥬': 'Leafy Green',
  '🥒': 'Cucumber',
  '🌶️': 'Hot Pepper',
  '🌽': 'Corn',
  '🥕': 'Carrot',
  '🧄': 'Garlic',
  '🧅': 'Onion',
  '🥔': 'Potato',
  '🍠': 'Roasted Sweet Potato',
  '🥐': 'Croissant',
  '🍞': 'Bread',
  '🥖': 'Baguette Bread',
  '🥨': 'Pretzel',
  '🧀': 'Cheese Wedge',
  '🥚': 'Egg',
  '🍳': 'Cooking',
  '🥞': 'Pancakes',
  '🧇': 'Waffle',
  '🥓': 'Bacon',
  '🥩': 'Cut of Meat',
  '🍗': 'Poultry Leg',
  '🍖': 'Meat on Bone',
  '🌭': 'Hot Dog',
  '🍔': 'Hamburger',
  '🍟': 'French Fries',
  '🍕': 'Pizza',
  '🥪': 'Sandwich',
  '🥙': 'Stuffed Flatbread',
  '🌮': 'Taco',
  '🌯': 'Burrito',
  '🥗': 'Green Salad',
  '🥘': 'Shallow Pan of Food',
  '🥫': 'Canned Food',
  '🍝': 'Spaghetti',
  '🍜': 'Steaming Bowl',
  '🍲': 'Pot of Food',
  '🍛': 'Curry Rice',
  '🍣': 'Sushi',
  '🍱': 'Bento Box',
  '🥟': 'Dumpling',
  '🍤': 'Fried Shrimp',
  '🍙': 'Rice Ball',
  '🍚': 'Cooked Rice',
  '🍘': 'Rice Cracker',
  '🍢': 'Oden',
  '🍡': 'Dango',
  '🍧': 'Shaved Ice',
  '🍨': 'Ice Cream',
  '🍦': 'Soft Ice Cream',
  '🥧': 'Pie',
  '🍰': 'Shortcake',
  '🎂': 'Birthday Cake',
  '🧁': 'Cupcake',
  '🍮': 'Custard',
  '🍭': 'Lollipop',
  '🍬': 'Candy',
  '🍫': 'Chocolate Bar',
  '🍿': 'Popcorn',
  '🍩': 'Doughnut',
  '🍪': 'Cookie',
  '☕️': 'Hot Beverage',
  '🍵': 'Teacup Without Handle',
  '🥤': 'Cup with Straw',
  '🧃': 'Beverage Box',
  '🍷': 'Wine Glass',
  '🍸': 'Cocktail Glass',
  '🍹': 'Tropical Drink',
  '🍺': 'Beer Mug',
  '🍻': 'Clinking Beer Mugs',
  '🥂': 'Clinking Glasses',
  '🥃': 'Tumbler Glass',
  '🧉': 'Mate',
  '🧊': 'Ice',

  // 🧳 Seyahat & Yerler (Travel & Places)
  '🌍': 'Globe Showing Europe-Africa',
  '🌎': 'Globe Showing Americas',
  '🌏': 'Globe Showing Asia-Australia',
  '🗺️': 'World Map',
  '🗾': 'Map of Japan',
  '🏔️': 'Snow-Capped Mountain',
  '⛰️': 'Mountain',
  '🌋': 'Volcano',
  '🗻': 'Mount Fuji',
  '🏕️': 'Camping',
  '🏖️': 'Beach with Umbrella',
  '🏜️': 'Desert',
  '🏝️': 'Desert Island',
  '🏞️': 'National Park',
  '🏟️': 'Stadium',
  '🏛️': 'Classical Building',
  '🏗️': 'Building Construction',
  '🧱': 'Brick',
  '🏠': 'House',
  '🏡': 'House with Garden',
  '🏢': 'Office Building',
  '🏣': 'Japanese Post Office',
  '🏤': 'Post Office',
  '🏥': 'Hospital',
  '🏦': 'Bank',
  '🏨': 'Hotel',
  '🏩': 'Love Hotel',
  '🏪': 'Convenience Store',
  '🏫': 'School',
  '🏬': 'Department Store',
  '🏭': 'Factory',
  '🏯': 'Japanese Castle',
  '🏰': 'Castle',
  '💒': 'Wedding',
  '🗼': 'Tokyo Tower',
  '🗽': 'Statue of Liberty',
  '⛪️': 'Church',
  '🕌': 'Mosque',
  '🕍': 'Synagogue',
  '⛩️': 'Shinto Shrine',
  '🕋': 'Kaaba',
  '⛲️': 'Fountain',
  '⛺️': 'Tent',
  '🌁': 'Foggy',
  '🌃': 'Night with Stars',
  '🏙️': 'Cityscape',
  '🌄': 'Sunrise Over Mountains',
  '🌅': 'Sunrise',
  '🌆': 'Cityscape at Dusk',
  '🌇': 'Sunset',
  '🌉': 'Bridge at Night',
  '🌌': 'Milky Way',
  '🎠': 'Carousel Horse',
  '🎡': 'Ferris Wheel',
  '🎢': 'Roller Coaster',
  '🚂': 'Locomotive',
  '🚃': 'Railway Car',
  '🚄': 'High-Speed Train',
  '🚅': 'Bullet Train',
  '🚆': 'Train',
  '🚇': 'Metro',
  '🚈': 'Light Rail',
  '🚉': 'Station',
  '🚊': 'Tram',
  '🚝': 'Monorail',
  '🚞': 'Mountain Railway',
  '🚋': 'Tram Car',
  '🚌': 'Bus',
  '🚍': 'Oncoming Bus',
  '🚎': 'Trolleybus',
  '🚐': 'Minibus',
  '🚑': 'Ambulance',
  '🚒': 'Fire Engine',
  '🚓': 'Police Car',
  '🚔': 'Oncoming Police Car',
  '🚕': 'Taxi',
  '🚖': 'Oncoming Taxi',
  '🚗': 'Automobile',
  '🚘': 'Oncoming Automobile',
  '🚙': 'Sport Utility Vehicle',
  '🏎️': 'Racing Car',
  '🚚': 'Delivery Truck',
  '🚛': 'Articulated Lorry',
  '🚜': 'Tractor',
  '🛻': 'Pickup Truck',
  '🚲': 'Bicycle',
  '🛴': 'Kick Scooter',
  '🛹': 'Skateboard',
  '🛼': 'Roller Skate',
  '🛵': 'Motor Scooter',
  '🏍️': 'Motorcycle',
  '🛺': 'Auto Rickshaw',
  '✈️': 'Airplane',
  '🛫': 'Airplane Departure',
  '🛬': 'Airplane Arrival',
  '🪂': 'Parachute',
  '💺': 'Seat',
  '🚁': 'Helicopter',
  '🛰️': 'Satellite',
  '🚀': 'Rocket',
  '🛸': 'Flying Saucer',
  '🚢': 'Ship',
  '⚓️': 'Anchor',
  '🪝': 'Hook',

  // 💡 Objeler (Objects)
  '⌚️': 'Watch',
  '📱': 'Mobile Phone',
  '💻': 'Laptop',
  '⌨️': 'Keyboard',
  '🖥️': 'Desktop Computer',
  '🖨️': 'Printer',
  '🖱️': 'Computer Mouse',
  '💾': 'Floppy Disk',
  '💿': 'Optical Disk',
  '📀': 'DVD',
  '🎥': 'Movie Camera',
  '🎞️': 'Film Frames',
  '📷': 'Camera',
  '📸': 'Camera with Flash',
  '📹': 'Video Camera',
  '📺': 'Television',
  '📻': 'Radio',
  '🎙️': 'Studio Microphone',
  '🎚️': 'Level Slider',
  '🎛️': 'Control Knobs',
  '☎️': 'Telephone',
  '📞': 'Telephone Receiver',
  '📟': 'Pager',
  '📠': 'Fax Machine',
  '🔋': 'Battery',
  '🔌': 'Electric Plug',
  '💡': 'Light Bulb',
  '🔦': 'Flashlight',
  '🕯️': 'Candle',
  '🧯': 'Fire Extinguisher',
  '🪔': 'Diya Lamp',
  '🧲': 'Magnet',
  '🧪': 'Test Tube',
  '🧫': 'Petri Dish',
  '🧬': 'DNA',
  '🩸': 'Drop of Blood',
  '💊': 'Pill',
  '💉': 'Syringe',
  '🩹': 'Adhesive Bandage',
  '🩼': 'Crutch',
  '🩺': 'Stethoscope',
  '🧷': 'Safety Pin',
  '🧹': 'Broom',
  '🧺': 'Basket',
  '🪣': 'Bucket',
  '🧻': 'Roll of Paper',
  '🪟': 'Window',
  '🪞': 'Mirror',
  '🚪': 'Door',
  '🛏️': 'Bed',
  '🪑': 'Chair',
  '🚽': 'Toilet',
  '🚿': 'Shower',
  '🛁': 'Bathtub',
  '🪠': 'Plunger',
  '🧴': 'Lotion Bottle',
  '🪥': 'Toothbrush',
  '🪒': 'Razor',
  '🧼': 'Soap',
  '🪮': 'Hair Pick',
  '🪶': 'Feather',
  '🧽': 'Sponge',
  '🧸': 'Teddy Bear',
  '🎁': 'Wrapped Gift',
  '🎈': 'Balloon',
  '🎉': 'Party Popper',
  '🎊': 'Confetti Ball',
  '🎀': 'Ribbon',
  '🎗️': 'Reminder Ribbon',
  '🏆': 'Trophy',
  '🥇': '1st Place Medal',
  '🥈': '2nd Place Medal',
  '🥉': '3rd Place Medal',
  '🏅': 'Sports Medal',
  '🎖️': 'Military Medal',
  '🧿': 'Nazar Amulet',
  '📿': 'Prayer Beads',
  '💎': 'Gem Stone',

  // ❤️ Semboller (Symbols)
  '❤️': 'Red Heart',
  '🧡': 'Orange Heart',
  '💛': 'Yellow Heart',
  '💚': 'Green Heart',
  '💙': 'Blue Heart',
  '💜': 'Purple Heart',
  '🤍': 'White Heart',
  '🤎': 'Brown Heart',
  '🖤': 'Black Heart',
  '💔': 'Broken Heart',
  '❣️': 'Heart Exclamation',
  '💕': 'Two Hearts',
  '💞': 'Revolving Hearts',
  '💓': 'Beating Heart',
  '💗': 'Growing Heart',
  '💖': 'Sparkling Heart',
  '💘': 'Heart with Arrow',
  '💝': 'Heart with Ribbon',
  '💟': 'Heart Decoration',
  '☮️': 'Peace Symbol',
  '✝️': 'Latin Cross',
  '☪️': 'Star and Crescent',
  '🕉️': 'Om',
  '☸️': 'Wheel of Dharma',
  '🪯': 'Khanda',
  '✡️': 'Star of David',
  '🔯': 'Dotted Six-Pointed Star',
  '🕎': 'Menorah',
  '☯️': 'Yin Yang',
  '☦️': 'Orthodox Cross',
  '🛐': 'Place of Worship',
  '⛎': 'Ophiuchus',
  '♈️': 'Aries',
  '♉️': 'Taurus',
  '♊️': 'Gemini',
  '♋️': 'Cancer',
  '♌️': 'Leo',
  '♍️': 'Virgo',
  '♎️': 'Libra',
  '♏️': 'Scorpio',
  '♐️': 'Sagittarius',
  '♑️': 'Capricorn',
  '♒️': 'Aquarius',
  '♓️': 'Pisces',
  '🆔': 'ID Button',
  '⚛️': 'Atom Symbol',
  '🉑': 'Japanese “Acceptable” Button',
  '☢️': 'Radioactive',
  '☣️': 'Biohazard',
  '📴': 'Mobile Phone Off',
  '📳': 'Vibration Mode',
  '🈶': 'Japanese “Not Free of Charge” Button',
  '🈚️': 'Japanese “Free of Charge” Button',
  '🈸': 'Japanese “Application” Button',
  '🈺': 'Japanese “Open for Business” Button',
  '🈷️': 'Japanese “Monthly Amount” Button',
  '✴️': 'Eight-Pointed Star',
  '🆚': 'VS Button',
  '💯': 'Hundred Points',
  '🈴': 'Japanese “Passing Grade” Button',
  '🈵': 'Japanese “No Vacancy” Button',
  '🈹': 'Japanese “Discount” Button',
  '🈲': 'Japanese “Prohibited” Button',
  '🅰️': 'A Button (Blood Type)',
  '🅱️': 'B Button (Blood Type)',
  '🆎': 'AB Button (Blood Type)',
  '🆑': 'CL Button',
  '🅾️': 'O Button (Blood Type)',
  '🆘': 'SOS Button',
  '❌': 'Cross Mark',
  '⭕️': 'Hollow Red Circle',
  '🛑': 'Stop Sign',
  '⛔️': 'No Entry',
  '📛': 'Name Badge',
  '🚫': 'Prohibited',
  '💢': 'Anger Symbol',
  '♨️': 'Hot Springs',
  '🚷': 'No Pedestrians',
  '🚯': 'No Littering',
  '🚳': 'No Bicycles',
  '🚱': 'Non-Potable Water',
  '🔞': 'No One Under Eighteen',
  '📵': 'No Mobile Phones',
  '🚭': 'No Smoking',
  '❗️': 'Red Exclamation Mark',
  '❕': 'White Exclamation Mark',
  '❓': 'Red Question Mark',
  '❔': 'White Question Mark',
  '‼️': 'Double Exclamation Mark',
  '⁉️': 'Exclamation Question Mark',
  '🔅': 'Dim Button',
  '🔆': 'Bright Button',
  '〽️': 'Part Alternation Mark',
  '⚠️': 'Warning',
  '🚸': 'Children Crossing',
  '🔱': 'Trident Emblem',
  '⚜️': 'Fleur-de-lis',
  '🔰': 'Japanese Symbol for Beginner',
  '♻️': 'Recycling Symbol',
  '✅': 'Check Mark Button',
  '🈯️': 'Japanese “Reserved” Button',
  '💹': 'Chart Increasing with Yen',
  '❇️': 'Sparkle',
  '✳️': 'Eight-Spoked Asterisk',
  '❎': 'Cross Mark Button',
  '🌐': 'Globe with Meridians',
  '💠': 'Diamond with a Dot',
  'Ⓜ️': 'Circled M',
  '🌀': 'Cyclone',
  '🅿️': 'P Button',
  '🔺': 'Red Triangle Pointed Up',
  '🔻': 'Red Triangle Pointed Down',
  '💤': 'Zzz',
  '🏧': 'ATM Sign',
  '🚾': 'Water Closet',
  '♿️': 'Wheelchair Symbol',
  '🚹': 'Men’s Room',
  '🚺': 'Women’s Room',
  '🚼': 'Baby Symbol',
  '🚻': 'Restroom',
  '🚮': 'Litter in Bin Sign',
  '🎦': 'Cinema',
  '📶': 'Antenna Bars',
  '🈁': 'Japanese “Here” Button',
  '🔣': 'Input Symbols',
  'ℹ️': 'Information',
  '🔤': 'Input Latin Letters',
  '🔡': 'Input Latin Lowercase',
  '🔠': 'Input Latin Uppercase',
  '🆖': 'NG Button',
  '🆗': 'OK Button',
  '🆙': 'UP! Button',
  '🆒': 'COOL Button',
  '🆕': 'NEW Button',
  '🆓': 'FREE Button',
  '0️⃣': 'Keycap: 0',
  '1️⃣': 'Keycap: 1',
  '2️⃣': 'Keycap: 2',
  '3️⃣': 'Keycap: 3',
  '4️⃣': 'Keycap: 4',
  '5️⃣': 'Keycap: 5',
  '6️⃣': 'Keycap: 6',
  '7️⃣': 'Keycap: 7',
  '8️⃣': 'Keycap: 8',
  '9️⃣': 'Keycap: 9',
  '🔟': 'Keycap: 10',
};
